### ISSUE TITLE
fix: repay exceeds borrow amount on testing

### ISSUE THREAD

**Issue by dargmuesli** [bitcoinvsalts/node-binance-trader#122]
Running the testing branch, repay does not seem to work yet:
`2021-09-07 16:47:43 | error | Failed to execute the trading sequence's after step: ExchangeError: binance {"code":-3015,"msg":"Repay amount exceeds borrow amount."}`
I need to check this when I got time.

**Comment by bitcoinvsalts** [comment]
ok let me know how it goes and thank you for your help

**Comment by dargmuesli** [comment]
Sadly, margin trading has been disabled for European users now so I cannot dig into that issue anymore. I'll close this ticket until someone faces this issue again, then we can reopen it of course :)
