### ISSUE TITLE
Deploy Heroku

### ISSUE THREAD

**Issue by ghostnetrn** [bitcoinvsalts/node-binance-trader#123]
We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.

**Comment by mauriil** [comment]
I got the same issue.... any updates?

**Comment by bitcoinvsalts** [comment]
I never experienced this issue. Can you post some screenshots?

**Comment by mauriil** [comment]
![image](https://user-images.githubusercontent.com/18168535/149177451-ca59bb49-b99d-4aff-94b3-5cd64eb42c16.png)

**Comment by bitcoinvsalts** [comment]
try to see what npm pkg is causing this issue

**Comment by dargmuesli** [comment]
@ghostnetrn @mauriil do you still face this issue?

**Comment by ghostnetrn** [comment]
Yes

Item could not be created:
We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.

**Comment by dargmuesli** [comment]
Sounds like something you'd need to take care of, @bitcoinvsalts?

**Comment by yamitha** [comment]
Hi, I also face this issue. Is there any way around this?

**Comment by dargmuesli** [comment]
As bitcoinvsalts.com is EOL, the heroku deployment won't be fixed anymore. The repo is kept as is and is to be understood as archived.
